//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by slsvcutil, version 4.0.50826.0
// 
namespace ServiceReference.MySisEvo.Web.DataServis
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Datas", Namespace="http://schemas.datacontract.org/2004/07/MySisEvo.Web.Classes")]
    public partial class Datas : object
    {
        
        private int ARC_SER1NOField;
        
        private int DT_1DField;
        
        private string DT_ADRESField;
        
        private string DT_BOYLAMField;
        
        private string DT_BOYLAM_HAMField;
        
        private bool DT_DURAKLAMAField;
        
        private string DT_ENLEMField;
        
        private string DT_ENLEM_HAMField;
        
        private string DT_H1ZField;
        
        private string DT_KONTAKField;
        
        private double DT_MESAFEField;
        
        private System.DateTime DT_TAR1HField;
        
        private System.DateTime DT_TAR1HKField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ARC_SER1NO
        {
            get
            {
                return this.ARC_SER1NOField;
            }
            set
            {
                this.ARC_SER1NOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DT_1D
        {
            get
            {
                return this.DT_1DField;
            }
            set
            {
                this.DT_1DField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DT_ADRES
        {
            get
            {
                return this.DT_ADRESField;
            }
            set
            {
                this.DT_ADRESField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DT_BOYLAM
        {
            get
            {
                return this.DT_BOYLAMField;
            }
            set
            {
                this.DT_BOYLAMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DT_BOYLAM_HAM
        {
            get
            {
                return this.DT_BOYLAM_HAMField;
            }
            set
            {
                this.DT_BOYLAM_HAMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DT_DURAKLAMA
        {
            get
            {
                return this.DT_DURAKLAMAField;
            }
            set
            {
                this.DT_DURAKLAMAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DT_ENLEM
        {
            get
            {
                return this.DT_ENLEMField;
            }
            set
            {
                this.DT_ENLEMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DT_ENLEM_HAM
        {
            get
            {
                return this.DT_ENLEM_HAMField;
            }
            set
            {
                this.DT_ENLEM_HAMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DT_H1Z
        {
            get
            {
                return this.DT_H1ZField;
            }
            set
            {
                this.DT_H1ZField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DT_KONTAK
        {
            get
            {
                return this.DT_KONTAKField;
            }
            set
            {
                this.DT_KONTAKField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double DT_MESAFE
        {
            get
            {
                return this.DT_MESAFEField;
            }
            set
            {
                this.DT_MESAFEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DT_TAR1H
        {
            get
            {
                return this.DT_TAR1HField;
            }
            set
            {
                this.DT_TAR1HField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DT_TAR1HK
        {
            get
            {
                return this.DT_TAR1HKField;
            }
            set
            {
                this.DT_TAR1HKField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Alarmlar", Namespace="http://schemas.datacontract.org/2004/07/MySisEvo.Web.Classes")]
    public partial class Alarmlar : object
    {
        
        private int ALRM_IDField;
        
        private string ALRM_KULField;
        
        private string ALRM_NOTField;
        
        private bool ALRM_OKUNDUField;
        
        private string ALRM_PLAKAField;
        
        private System.DateTime ALRM_TARField;
        
        private string ALRM_TURField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ALRM_ID
        {
            get
            {
                return this.ALRM_IDField;
            }
            set
            {
                this.ALRM_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALRM_KUL
        {
            get
            {
                return this.ALRM_KULField;
            }
            set
            {
                this.ALRM_KULField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALRM_NOT
        {
            get
            {
                return this.ALRM_NOTField;
            }
            set
            {
                this.ALRM_NOTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ALRM_OKUNDU
        {
            get
            {
                return this.ALRM_OKUNDUField;
            }
            set
            {
                this.ALRM_OKUNDUField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALRM_PLAKA
        {
            get
            {
                return this.ALRM_PLAKAField;
            }
            set
            {
                this.ALRM_PLAKAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ALRM_TAR
        {
            get
            {
                return this.ALRM_TARField;
            }
            set
            {
                this.ALRM_TARField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALRM_TUR
        {
            get
            {
                return this.ALRM_TURField;
            }
            set
            {
                this.ALRM_TURField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlarmT", Namespace="http://schemas.datacontract.org/2004/07/MySisEvo.Web.Classes")]
    public partial class AlarmT : object
    {
        
        private string TNM_ARCField;
        
        private System.DateTime TNM_DURAKLAMAField;
        
        private string TNM_EPOSTAField;
        
        private string TNM_GSMField;
        
        private byte TNM_HZLMTField;
        
        private int TNM_IDField;
        
        private string TNM_KULField;
        
        private string TNM_MESA1Field;
        
        private System.DateTime TNM_ROLANTField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TNM_ARC
        {
            get
            {
                return this.TNM_ARCField;
            }
            set
            {
                this.TNM_ARCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TNM_DURAKLAMA
        {
            get
            {
                return this.TNM_DURAKLAMAField;
            }
            set
            {
                this.TNM_DURAKLAMAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TNM_EPOSTA
        {
            get
            {
                return this.TNM_EPOSTAField;
            }
            set
            {
                this.TNM_EPOSTAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TNM_GSM
        {
            get
            {
                return this.TNM_GSMField;
            }
            set
            {
                this.TNM_GSMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte TNM_HZLMT
        {
            get
            {
                return this.TNM_HZLMTField;
            }
            set
            {
                this.TNM_HZLMTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TNM_ID
        {
            get
            {
                return this.TNM_IDField;
            }
            set
            {
                this.TNM_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TNM_KUL
        {
            get
            {
                return this.TNM_KULField;
            }
            set
            {
                this.TNM_KULField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TNM_MESA1
        {
            get
            {
                return this.TNM_MESA1Field;
            }
            set
            {
                this.TNM_MESA1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TNM_ROLANT
        {
            get
            {
                return this.TNM_ROLANTField;
            }
            set
            {
                this.TNM_ROLANTField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Araclar", Namespace="http://schemas.datacontract.org/2004/07/MySisEvo.Web.Classes")]
    public partial class Araclar : object
    {
        
        private string ARC_CINSField;
        
        private string ARC_ICONField;
        
        private int ARC_IDField;
        
        private string ARC_KONTAKField;
        
        private string ARC_KOPMAField;
        
        private string ARC_MARKAField;
        
        private string ARC_MODELField;
        
        private string ARC_PLAKAField;
        
        private string ARC_RENKField;
        
        private string ARC_RES1MField;
        
        private string ARC_SAHIBIField;
        
        private string ARC_SASINOField;
        
        private int ARC_SERINOField;
        
        private string ARC_TELField;
        
        private int CHZ_IDField;
        
        private int FRM_IDField;
        
        private int GRP_IDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ARC_CINS
        {
            get
            {
                return this.ARC_CINSField;
            }
            set
            {
                this.ARC_CINSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ARC_ICON
        {
            get
            {
                return this.ARC_ICONField;
            }
            set
            {
                this.ARC_ICONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ARC_ID
        {
            get
            {
                return this.ARC_IDField;
            }
            set
            {
                this.ARC_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ARC_KONTAK
        {
            get
            {
                return this.ARC_KONTAKField;
            }
            set
            {
                this.ARC_KONTAKField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ARC_KOPMA
        {
            get
            {
                return this.ARC_KOPMAField;
            }
            set
            {
                this.ARC_KOPMAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ARC_MARKA
        {
            get
            {
                return this.ARC_MARKAField;
            }
            set
            {
                this.ARC_MARKAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ARC_MODEL
        {
            get
            {
                return this.ARC_MODELField;
            }
            set
            {
                this.ARC_MODELField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ARC_PLAKA
        {
            get
            {
                return this.ARC_PLAKAField;
            }
            set
            {
                this.ARC_PLAKAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ARC_RENK
        {
            get
            {
                return this.ARC_RENKField;
            }
            set
            {
                this.ARC_RENKField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ARC_RES1M
        {
            get
            {
                return this.ARC_RES1MField;
            }
            set
            {
                this.ARC_RES1MField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ARC_SAHIBI
        {
            get
            {
                return this.ARC_SAHIBIField;
            }
            set
            {
                this.ARC_SAHIBIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ARC_SASINO
        {
            get
            {
                return this.ARC_SASINOField;
            }
            set
            {
                this.ARC_SASINOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ARC_SERINO
        {
            get
            {
                return this.ARC_SERINOField;
            }
            set
            {
                this.ARC_SERINOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ARC_TEL
        {
            get
            {
                return this.ARC_TELField;
            }
            set
            {
                this.ARC_TELField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CHZ_ID
        {
            get
            {
                return this.CHZ_IDField;
            }
            set
            {
                this.CHZ_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FRM_ID
        {
            get
            {
                return this.FRM_IDField;
            }
            set
            {
                this.FRM_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GRP_ID
        {
            get
            {
                return this.GRP_IDField;
            }
            set
            {
                this.GRP_IDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kullanici", Namespace="http://schemas.datacontract.org/2004/07/MySisEvo.Web.Classes")]
    public partial class Kullanici : object
    {
        
        private int DenemeField;
        
        private int FRM_1DField;
        
        private string KUL_ADField;
        
        private int KUL_IDField;
        
        private string KUL_SIFREField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Deneme
        {
            get
            {
                return this.DenemeField;
            }
            set
            {
                this.DenemeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FRM_1D
        {
            get
            {
                return this.FRM_1DField;
            }
            set
            {
                this.FRM_1DField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KUL_AD
        {
            get
            {
                return this.KUL_ADField;
            }
            set
            {
                this.KUL_ADField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KUL_ID
        {
            get
            {
                return this.KUL_IDField;
            }
            set
            {
                this.KUL_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KUL_SIFRE
        {
            get
            {
                return this.KUL_SIFREField;
            }
            set
            {
                this.KUL_SIFREField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="ServiceReference.MySisEvo.Web.DataServis.DataServis")]
    public interface DataServis
    {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:DataServis/getData", ReplyAction="urn:DataServis/getDataResponse")]
        System.IAsyncResult BegingetData(int serino, System.AsyncCallback callback, object asyncState);
        
        ServiceReference.MySisEvo.Web.DataServis.Datas EndgetData(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:DataServis/getDatas", ReplyAction="urn:DataServis/getDatasResponse")]
        System.IAsyncResult BegingetDatas(string[] serinolar, System.AsyncCallback callback, object asyncState);
        
        ServiceReference.MySisEvo.Web.DataServis.Datas[] EndgetDatas(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:DataServis/getDataList", ReplyAction="urn:DataServis/getDataListResponse")]
        System.IAsyncResult BegingetDataList(int serino, System.DateTime basTar, System.DateTime bitTar, System.AsyncCallback callback, object asyncState);
        
        ServiceReference.MySisEvo.Web.DataServis.Datas[] EndgetDataList(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:DataServis/getDataListXml", ReplyAction="urn:DataServis/getDataListXmlResponse")]
        System.IAsyncResult BegingetDataListXml(int serino, System.DateTime basTar, System.DateTime bitTar, System.AsyncCallback callback, object asyncState);
        
        ServiceReference.MySisEvo.Web.DataServis.Datas[] EndgetDataListXml(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:DataServis/getAlarmlar", ReplyAction="urn:DataServis/getAlarmlarResponse")]
        System.IAsyncResult BegingetAlarmlar(string kul, System.AsyncCallback callback, object asyncState);
        
        ServiceReference.MySisEvo.Web.DataServis.Alarmlar[] EndgetAlarmlar(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:DataServis/setAlarmTanim", ReplyAction="urn:DataServis/setAlarmTanimResponse")]
        System.IAsyncResult BeginsetAlarmTanim(string Serinolar, ServiceReference.MySisEvo.Web.DataServis.AlarmT AlarmTan, System.AsyncCallback callback, object asyncState);
        
        void EndsetAlarmTanim(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:DataServis/getAraclar", ReplyAction="urn:DataServis/getAraclarResponse")]
        System.IAsyncResult BegingetAraclar(string kulAd, System.AsyncCallback callback, object asyncState);
        
        ServiceReference.MySisEvo.Web.DataServis.Araclar[] EndgetAraclar(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:DataServis/updateArac", ReplyAction="urn:DataServis/updateAracResponse")]
        System.IAsyncResult BeginupdateArac(ServiceReference.MySisEvo.Web.DataServis.Araclar arac, System.AsyncCallback callback, object asyncState);
        
        void EndupdateArac(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:DataServis/getKullanici", ReplyAction="urn:DataServis/getKullaniciResponse")]
        System.IAsyncResult BegingetKullanici(string kulAd, string kulSifre, System.AsyncCallback callback, object asyncState);
        
        ServiceReference.MySisEvo.Web.DataServis.Kullanici EndgetKullanici(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DataServisChannel : ServiceReference.MySisEvo.Web.DataServis.DataServis, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public getDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public ServiceReference.MySisEvo.Web.DataServis.Datas Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((ServiceReference.MySisEvo.Web.DataServis.Datas)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getDatasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public getDatasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public ServiceReference.MySisEvo.Web.DataServis.Datas[] Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((ServiceReference.MySisEvo.Web.DataServis.Datas[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getDataListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public getDataListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public ServiceReference.MySisEvo.Web.DataServis.Datas[] Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((ServiceReference.MySisEvo.Web.DataServis.Datas[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getDataListXmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public getDataListXmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public ServiceReference.MySisEvo.Web.DataServis.Datas[] Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((ServiceReference.MySisEvo.Web.DataServis.Datas[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getAlarmlarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public getAlarmlarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public ServiceReference.MySisEvo.Web.DataServis.Alarmlar[] Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((ServiceReference.MySisEvo.Web.DataServis.Alarmlar[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getAraclarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public getAraclarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public ServiceReference.MySisEvo.Web.DataServis.Araclar[] Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((ServiceReference.MySisEvo.Web.DataServis.Araclar[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getKullaniciCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public getKullaniciCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public ServiceReference.MySisEvo.Web.DataServis.Kullanici Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((ServiceReference.MySisEvo.Web.DataServis.Kullanici)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServisClient : System.ServiceModel.ClientBase<ServiceReference.MySisEvo.Web.DataServis.DataServis>, ServiceReference.MySisEvo.Web.DataServis.DataServis
    {
        
        private BeginOperationDelegate onBegingetDataDelegate;
        
        private EndOperationDelegate onEndgetDataDelegate;
        
        private System.Threading.SendOrPostCallback ongetDataCompletedDelegate;
        
        private BeginOperationDelegate onBegingetDatasDelegate;
        
        private EndOperationDelegate onEndgetDatasDelegate;
        
        private System.Threading.SendOrPostCallback ongetDatasCompletedDelegate;
        
        private BeginOperationDelegate onBegingetDataListDelegate;
        
        private EndOperationDelegate onEndgetDataListDelegate;
        
        private System.Threading.SendOrPostCallback ongetDataListCompletedDelegate;
        
        private BeginOperationDelegate onBegingetDataListXmlDelegate;
        
        private EndOperationDelegate onEndgetDataListXmlDelegate;
        
        private System.Threading.SendOrPostCallback ongetDataListXmlCompletedDelegate;
        
        private BeginOperationDelegate onBegingetAlarmlarDelegate;
        
        private EndOperationDelegate onEndgetAlarmlarDelegate;
        
        private System.Threading.SendOrPostCallback ongetAlarmlarCompletedDelegate;
        
        private BeginOperationDelegate onBeginsetAlarmTanimDelegate;
        
        private EndOperationDelegate onEndsetAlarmTanimDelegate;
        
        private System.Threading.SendOrPostCallback onsetAlarmTanimCompletedDelegate;
        
        private BeginOperationDelegate onBegingetAraclarDelegate;
        
        private EndOperationDelegate onEndgetAraclarDelegate;
        
        private System.Threading.SendOrPostCallback ongetAraclarCompletedDelegate;
        
        private BeginOperationDelegate onBeginupdateAracDelegate;
        
        private EndOperationDelegate onEndupdateAracDelegate;
        
        private System.Threading.SendOrPostCallback onupdateAracCompletedDelegate;
        
        private BeginOperationDelegate onBegingetKullaniciDelegate;
        
        private EndOperationDelegate onEndgetKullaniciDelegate;
        
        private System.Threading.SendOrPostCallback ongetKullaniciCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public DataServisClient()
        {
        }
        
        public DataServisClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public DataServisClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public DataServisClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public DataServisClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Net.CookieContainer CookieContainer
        {
            get
            {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null))
                {
                    return httpCookieContainerManager.CookieContainer;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null))
                {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else
                {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<getDataCompletedEventArgs> getDataCompleted;
        
        public event System.EventHandler<getDatasCompletedEventArgs> getDatasCompleted;
        
        public event System.EventHandler<getDataListCompletedEventArgs> getDataListCompleted;
        
        public event System.EventHandler<getDataListXmlCompletedEventArgs> getDataListXmlCompleted;
        
        public event System.EventHandler<getAlarmlarCompletedEventArgs> getAlarmlarCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> setAlarmTanimCompleted;
        
        public event System.EventHandler<getAraclarCompletedEventArgs> getAraclarCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> updateAracCompleted;
        
        public event System.EventHandler<getKullaniciCompletedEventArgs> getKullaniciCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ServiceReference.MySisEvo.Web.DataServis.DataServis.BegingetData(int serino, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BegingetData(serino, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference.MySisEvo.Web.DataServis.Datas ServiceReference.MySisEvo.Web.DataServis.DataServis.EndgetData(System.IAsyncResult result)
        {
            return base.Channel.EndgetData(result);
        }
        
        private System.IAsyncResult OnBegingetData(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            int serino = ((int)(inValues[0]));
            return ((ServiceReference.MySisEvo.Web.DataServis.DataServis)(this)).BegingetData(serino, callback, asyncState);
        }
        
        private object[] OnEndgetData(System.IAsyncResult result)
        {
            ServiceReference.MySisEvo.Web.DataServis.Datas retVal = ((ServiceReference.MySisEvo.Web.DataServis.DataServis)(this)).EndgetData(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetDataCompleted(object state)
        {
            if ((this.getDataCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getDataCompleted(this, new getDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getDataAsync(int serino)
        {
            this.getDataAsync(serino, null);
        }
        
        public void getDataAsync(int serino, object userState)
        {
            if ((this.onBegingetDataDelegate == null))
            {
                this.onBegingetDataDelegate = new BeginOperationDelegate(this.OnBegingetData);
            }
            if ((this.onEndgetDataDelegate == null))
            {
                this.onEndgetDataDelegate = new EndOperationDelegate(this.OnEndgetData);
            }
            if ((this.ongetDataCompletedDelegate == null))
            {
                this.ongetDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetDataCompleted);
            }
            base.InvokeAsync(this.onBegingetDataDelegate, new object[] {
                        serino}, this.onEndgetDataDelegate, this.ongetDataCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ServiceReference.MySisEvo.Web.DataServis.DataServis.BegingetDatas(string[] serinolar, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BegingetDatas(serinolar, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference.MySisEvo.Web.DataServis.Datas[] ServiceReference.MySisEvo.Web.DataServis.DataServis.EndgetDatas(System.IAsyncResult result)
        {
            return base.Channel.EndgetDatas(result);
        }
        
        private System.IAsyncResult OnBegingetDatas(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            string[] serinolar = ((string[])(inValues[0]));
            return ((ServiceReference.MySisEvo.Web.DataServis.DataServis)(this)).BegingetDatas(serinolar, callback, asyncState);
        }
        
        private object[] OnEndgetDatas(System.IAsyncResult result)
        {
            ServiceReference.MySisEvo.Web.DataServis.Datas[] retVal = ((ServiceReference.MySisEvo.Web.DataServis.DataServis)(this)).EndgetDatas(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetDatasCompleted(object state)
        {
            if ((this.getDatasCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getDatasCompleted(this, new getDatasCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getDatasAsync(string[] serinolar)
        {
            this.getDatasAsync(serinolar, null);
        }
        
        public void getDatasAsync(string[] serinolar, object userState)
        {
            if ((this.onBegingetDatasDelegate == null))
            {
                this.onBegingetDatasDelegate = new BeginOperationDelegate(this.OnBegingetDatas);
            }
            if ((this.onEndgetDatasDelegate == null))
            {
                this.onEndgetDatasDelegate = new EndOperationDelegate(this.OnEndgetDatas);
            }
            if ((this.ongetDatasCompletedDelegate == null))
            {
                this.ongetDatasCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetDatasCompleted);
            }
            base.InvokeAsync(this.onBegingetDatasDelegate, new object[] {
                        serinolar}, this.onEndgetDatasDelegate, this.ongetDatasCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ServiceReference.MySisEvo.Web.DataServis.DataServis.BegingetDataList(int serino, System.DateTime basTar, System.DateTime bitTar, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BegingetDataList(serino, basTar, bitTar, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference.MySisEvo.Web.DataServis.Datas[] ServiceReference.MySisEvo.Web.DataServis.DataServis.EndgetDataList(System.IAsyncResult result)
        {
            return base.Channel.EndgetDataList(result);
        }
        
        private System.IAsyncResult OnBegingetDataList(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            int serino = ((int)(inValues[0]));
            System.DateTime basTar = ((System.DateTime)(inValues[1]));
            System.DateTime bitTar = ((System.DateTime)(inValues[2]));
            return ((ServiceReference.MySisEvo.Web.DataServis.DataServis)(this)).BegingetDataList(serino, basTar, bitTar, callback, asyncState);
        }
        
        private object[] OnEndgetDataList(System.IAsyncResult result)
        {
            ServiceReference.MySisEvo.Web.DataServis.Datas[] retVal = ((ServiceReference.MySisEvo.Web.DataServis.DataServis)(this)).EndgetDataList(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetDataListCompleted(object state)
        {
            if ((this.getDataListCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getDataListCompleted(this, new getDataListCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getDataListAsync(int serino, System.DateTime basTar, System.DateTime bitTar)
        {
            this.getDataListAsync(serino, basTar, bitTar, null);
        }
        
        public void getDataListAsync(int serino, System.DateTime basTar, System.DateTime bitTar, object userState)
        {
            if ((this.onBegingetDataListDelegate == null))
            {
                this.onBegingetDataListDelegate = new BeginOperationDelegate(this.OnBegingetDataList);
            }
            if ((this.onEndgetDataListDelegate == null))
            {
                this.onEndgetDataListDelegate = new EndOperationDelegate(this.OnEndgetDataList);
            }
            if ((this.ongetDataListCompletedDelegate == null))
            {
                this.ongetDataListCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetDataListCompleted);
            }
            base.InvokeAsync(this.onBegingetDataListDelegate, new object[] {
                        serino,
                        basTar,
                        bitTar}, this.onEndgetDataListDelegate, this.ongetDataListCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ServiceReference.MySisEvo.Web.DataServis.DataServis.BegingetDataListXml(int serino, System.DateTime basTar, System.DateTime bitTar, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BegingetDataListXml(serino, basTar, bitTar, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference.MySisEvo.Web.DataServis.Datas[] ServiceReference.MySisEvo.Web.DataServis.DataServis.EndgetDataListXml(System.IAsyncResult result)
        {
            return base.Channel.EndgetDataListXml(result);
        }
        
        private System.IAsyncResult OnBegingetDataListXml(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            int serino = ((int)(inValues[0]));
            System.DateTime basTar = ((System.DateTime)(inValues[1]));
            System.DateTime bitTar = ((System.DateTime)(inValues[2]));
            return ((ServiceReference.MySisEvo.Web.DataServis.DataServis)(this)).BegingetDataListXml(serino, basTar, bitTar, callback, asyncState);
        }
        
        private object[] OnEndgetDataListXml(System.IAsyncResult result)
        {
            ServiceReference.MySisEvo.Web.DataServis.Datas[] retVal = ((ServiceReference.MySisEvo.Web.DataServis.DataServis)(this)).EndgetDataListXml(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetDataListXmlCompleted(object state)
        {
            if ((this.getDataListXmlCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getDataListXmlCompleted(this, new getDataListXmlCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getDataListXmlAsync(int serino, System.DateTime basTar, System.DateTime bitTar)
        {
            this.getDataListXmlAsync(serino, basTar, bitTar, null);
        }
        
        public void getDataListXmlAsync(int serino, System.DateTime basTar, System.DateTime bitTar, object userState)
        {
            if ((this.onBegingetDataListXmlDelegate == null))
            {
                this.onBegingetDataListXmlDelegate = new BeginOperationDelegate(this.OnBegingetDataListXml);
            }
            if ((this.onEndgetDataListXmlDelegate == null))
            {
                this.onEndgetDataListXmlDelegate = new EndOperationDelegate(this.OnEndgetDataListXml);
            }
            if ((this.ongetDataListXmlCompletedDelegate == null))
            {
                this.ongetDataListXmlCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetDataListXmlCompleted);
            }
            base.InvokeAsync(this.onBegingetDataListXmlDelegate, new object[] {
                        serino,
                        basTar,
                        bitTar}, this.onEndgetDataListXmlDelegate, this.ongetDataListXmlCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ServiceReference.MySisEvo.Web.DataServis.DataServis.BegingetAlarmlar(string kul, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BegingetAlarmlar(kul, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference.MySisEvo.Web.DataServis.Alarmlar[] ServiceReference.MySisEvo.Web.DataServis.DataServis.EndgetAlarmlar(System.IAsyncResult result)
        {
            return base.Channel.EndgetAlarmlar(result);
        }
        
        private System.IAsyncResult OnBegingetAlarmlar(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            string kul = ((string)(inValues[0]));
            return ((ServiceReference.MySisEvo.Web.DataServis.DataServis)(this)).BegingetAlarmlar(kul, callback, asyncState);
        }
        
        private object[] OnEndgetAlarmlar(System.IAsyncResult result)
        {
            ServiceReference.MySisEvo.Web.DataServis.Alarmlar[] retVal = ((ServiceReference.MySisEvo.Web.DataServis.DataServis)(this)).EndgetAlarmlar(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetAlarmlarCompleted(object state)
        {
            if ((this.getAlarmlarCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getAlarmlarCompleted(this, new getAlarmlarCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getAlarmlarAsync(string kul)
        {
            this.getAlarmlarAsync(kul, null);
        }
        
        public void getAlarmlarAsync(string kul, object userState)
        {
            if ((this.onBegingetAlarmlarDelegate == null))
            {
                this.onBegingetAlarmlarDelegate = new BeginOperationDelegate(this.OnBegingetAlarmlar);
            }
            if ((this.onEndgetAlarmlarDelegate == null))
            {
                this.onEndgetAlarmlarDelegate = new EndOperationDelegate(this.OnEndgetAlarmlar);
            }
            if ((this.ongetAlarmlarCompletedDelegate == null))
            {
                this.ongetAlarmlarCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetAlarmlarCompleted);
            }
            base.InvokeAsync(this.onBegingetAlarmlarDelegate, new object[] {
                        kul}, this.onEndgetAlarmlarDelegate, this.ongetAlarmlarCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ServiceReference.MySisEvo.Web.DataServis.DataServis.BeginsetAlarmTanim(string Serinolar, ServiceReference.MySisEvo.Web.DataServis.AlarmT AlarmTan, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginsetAlarmTanim(Serinolar, AlarmTan, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ServiceReference.MySisEvo.Web.DataServis.DataServis.EndsetAlarmTanim(System.IAsyncResult result)
        {
            base.Channel.EndsetAlarmTanim(result);
        }
        
        private System.IAsyncResult OnBeginsetAlarmTanim(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            string Serinolar = ((string)(inValues[0]));
            ServiceReference.MySisEvo.Web.DataServis.AlarmT AlarmTan = ((ServiceReference.MySisEvo.Web.DataServis.AlarmT)(inValues[1]));
            return ((ServiceReference.MySisEvo.Web.DataServis.DataServis)(this)).BeginsetAlarmTanim(Serinolar, AlarmTan, callback, asyncState);
        }
        
        private object[] OnEndsetAlarmTanim(System.IAsyncResult result)
        {
            ((ServiceReference.MySisEvo.Web.DataServis.DataServis)(this)).EndsetAlarmTanim(result);
            return null;
        }
        
        private void OnsetAlarmTanimCompleted(object state)
        {
            if ((this.setAlarmTanimCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.setAlarmTanimCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void setAlarmTanimAsync(string Serinolar, ServiceReference.MySisEvo.Web.DataServis.AlarmT AlarmTan)
        {
            this.setAlarmTanimAsync(Serinolar, AlarmTan, null);
        }
        
        public void setAlarmTanimAsync(string Serinolar, ServiceReference.MySisEvo.Web.DataServis.AlarmT AlarmTan, object userState)
        {
            if ((this.onBeginsetAlarmTanimDelegate == null))
            {
                this.onBeginsetAlarmTanimDelegate = new BeginOperationDelegate(this.OnBeginsetAlarmTanim);
            }
            if ((this.onEndsetAlarmTanimDelegate == null))
            {
                this.onEndsetAlarmTanimDelegate = new EndOperationDelegate(this.OnEndsetAlarmTanim);
            }
            if ((this.onsetAlarmTanimCompletedDelegate == null))
            {
                this.onsetAlarmTanimCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnsetAlarmTanimCompleted);
            }
            base.InvokeAsync(this.onBeginsetAlarmTanimDelegate, new object[] {
                        Serinolar,
                        AlarmTan}, this.onEndsetAlarmTanimDelegate, this.onsetAlarmTanimCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ServiceReference.MySisEvo.Web.DataServis.DataServis.BegingetAraclar(string kulAd, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BegingetAraclar(kulAd, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference.MySisEvo.Web.DataServis.Araclar[] ServiceReference.MySisEvo.Web.DataServis.DataServis.EndgetAraclar(System.IAsyncResult result)
        {
            return base.Channel.EndgetAraclar(result);
        }
        
        private System.IAsyncResult OnBegingetAraclar(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            string kulAd = ((string)(inValues[0]));
            return ((ServiceReference.MySisEvo.Web.DataServis.DataServis)(this)).BegingetAraclar(kulAd, callback, asyncState);
        }
        
        private object[] OnEndgetAraclar(System.IAsyncResult result)
        {
            ServiceReference.MySisEvo.Web.DataServis.Araclar[] retVal = ((ServiceReference.MySisEvo.Web.DataServis.DataServis)(this)).EndgetAraclar(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetAraclarCompleted(object state)
        {
            if ((this.getAraclarCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getAraclarCompleted(this, new getAraclarCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getAraclarAsync(string kulAd)
        {
            this.getAraclarAsync(kulAd, null);
        }
        
        public void getAraclarAsync(string kulAd, object userState)
        {
            if ((this.onBegingetAraclarDelegate == null))
            {
                this.onBegingetAraclarDelegate = new BeginOperationDelegate(this.OnBegingetAraclar);
            }
            if ((this.onEndgetAraclarDelegate == null))
            {
                this.onEndgetAraclarDelegate = new EndOperationDelegate(this.OnEndgetAraclar);
            }
            if ((this.ongetAraclarCompletedDelegate == null))
            {
                this.ongetAraclarCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetAraclarCompleted);
            }
            base.InvokeAsync(this.onBegingetAraclarDelegate, new object[] {
                        kulAd}, this.onEndgetAraclarDelegate, this.ongetAraclarCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ServiceReference.MySisEvo.Web.DataServis.DataServis.BeginupdateArac(ServiceReference.MySisEvo.Web.DataServis.Araclar arac, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginupdateArac(arac, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ServiceReference.MySisEvo.Web.DataServis.DataServis.EndupdateArac(System.IAsyncResult result)
        {
            base.Channel.EndupdateArac(result);
        }
        
        private System.IAsyncResult OnBeginupdateArac(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            ServiceReference.MySisEvo.Web.DataServis.Araclar arac = ((ServiceReference.MySisEvo.Web.DataServis.Araclar)(inValues[0]));
            return ((ServiceReference.MySisEvo.Web.DataServis.DataServis)(this)).BeginupdateArac(arac, callback, asyncState);
        }
        
        private object[] OnEndupdateArac(System.IAsyncResult result)
        {
            ((ServiceReference.MySisEvo.Web.DataServis.DataServis)(this)).EndupdateArac(result);
            return null;
        }
        
        private void OnupdateAracCompleted(object state)
        {
            if ((this.updateAracCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.updateAracCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void updateAracAsync(ServiceReference.MySisEvo.Web.DataServis.Araclar arac)
        {
            this.updateAracAsync(arac, null);
        }
        
        public void updateAracAsync(ServiceReference.MySisEvo.Web.DataServis.Araclar arac, object userState)
        {
            if ((this.onBeginupdateAracDelegate == null))
            {
                this.onBeginupdateAracDelegate = new BeginOperationDelegate(this.OnBeginupdateArac);
            }
            if ((this.onEndupdateAracDelegate == null))
            {
                this.onEndupdateAracDelegate = new EndOperationDelegate(this.OnEndupdateArac);
            }
            if ((this.onupdateAracCompletedDelegate == null))
            {
                this.onupdateAracCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnupdateAracCompleted);
            }
            base.InvokeAsync(this.onBeginupdateAracDelegate, new object[] {
                        arac}, this.onEndupdateAracDelegate, this.onupdateAracCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ServiceReference.MySisEvo.Web.DataServis.DataServis.BegingetKullanici(string kulAd, string kulSifre, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BegingetKullanici(kulAd, kulSifre, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference.MySisEvo.Web.DataServis.Kullanici ServiceReference.MySisEvo.Web.DataServis.DataServis.EndgetKullanici(System.IAsyncResult result)
        {
            return base.Channel.EndgetKullanici(result);
        }
        
        private System.IAsyncResult OnBegingetKullanici(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            string kulAd = ((string)(inValues[0]));
            string kulSifre = ((string)(inValues[1]));
            return ((ServiceReference.MySisEvo.Web.DataServis.DataServis)(this)).BegingetKullanici(kulAd, kulSifre, callback, asyncState);
        }
        
        private object[] OnEndgetKullanici(System.IAsyncResult result)
        {
            ServiceReference.MySisEvo.Web.DataServis.Kullanici retVal = ((ServiceReference.MySisEvo.Web.DataServis.DataServis)(this)).EndgetKullanici(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetKullaniciCompleted(object state)
        {
            if ((this.getKullaniciCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getKullaniciCompleted(this, new getKullaniciCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getKullaniciAsync(string kulAd, string kulSifre)
        {
            this.getKullaniciAsync(kulAd, kulSifre, null);
        }
        
        public void getKullaniciAsync(string kulAd, string kulSifre, object userState)
        {
            if ((this.onBegingetKullaniciDelegate == null))
            {
                this.onBegingetKullaniciDelegate = new BeginOperationDelegate(this.OnBegingetKullanici);
            }
            if ((this.onEndgetKullaniciDelegate == null))
            {
                this.onEndgetKullaniciDelegate = new EndOperationDelegate(this.OnEndgetKullanici);
            }
            if ((this.ongetKullaniciCompletedDelegate == null))
            {
                this.ongetKullaniciCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetKullaniciCompleted);
            }
            base.InvokeAsync(this.onBegingetKullaniciDelegate, new object[] {
                        kulAd,
                        kulSifre}, this.onEndgetKullaniciDelegate, this.ongetKullaniciCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result)
        {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state)
        {
            if ((this.OpenCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync()
        {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState)
        {
            if ((this.onBeginOpenDelegate == null))
            {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null))
            {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null))
            {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result)
        {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state)
        {
            if ((this.CloseCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync()
        {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState)
        {
            if ((this.onBeginCloseDelegate == null))
            {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null))
            {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null))
            {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override ServiceReference.MySisEvo.Web.DataServis.DataServis CreateChannel()
        {
            return new DataServisClientChannel(this);
        }
        
        private class DataServisClientChannel : ChannelBase<ServiceReference.MySisEvo.Web.DataServis.DataServis>, ServiceReference.MySisEvo.Web.DataServis.DataServis
        {
            
            public DataServisClientChannel(System.ServiceModel.ClientBase<ServiceReference.MySisEvo.Web.DataServis.DataServis> client) : 
                    base(client)
            {
            }
            
            public System.IAsyncResult BegingetData(int serino, System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[1];
                _args[0] = serino;
                System.IAsyncResult _result = base.BeginInvoke("getData", _args, callback, asyncState);
                return _result;
            }
            
            public ServiceReference.MySisEvo.Web.DataServis.Datas EndgetData(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                ServiceReference.MySisEvo.Web.DataServis.Datas _result = ((ServiceReference.MySisEvo.Web.DataServis.Datas)(base.EndInvoke("getData", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetDatas(string[] serinolar, System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[1];
                _args[0] = serinolar;
                System.IAsyncResult _result = base.BeginInvoke("getDatas", _args, callback, asyncState);
                return _result;
            }
            
            public ServiceReference.MySisEvo.Web.DataServis.Datas[] EndgetDatas(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                ServiceReference.MySisEvo.Web.DataServis.Datas[] _result = ((ServiceReference.MySisEvo.Web.DataServis.Datas[])(base.EndInvoke("getDatas", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetDataList(int serino, System.DateTime basTar, System.DateTime bitTar, System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[3];
                _args[0] = serino;
                _args[1] = basTar;
                _args[2] = bitTar;
                System.IAsyncResult _result = base.BeginInvoke("getDataList", _args, callback, asyncState);
                return _result;
            }
            
            public ServiceReference.MySisEvo.Web.DataServis.Datas[] EndgetDataList(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                ServiceReference.MySisEvo.Web.DataServis.Datas[] _result = ((ServiceReference.MySisEvo.Web.DataServis.Datas[])(base.EndInvoke("getDataList", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetDataListXml(int serino, System.DateTime basTar, System.DateTime bitTar, System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[3];
                _args[0] = serino;
                _args[1] = basTar;
                _args[2] = bitTar;
                System.IAsyncResult _result = base.BeginInvoke("getDataListXml", _args, callback, asyncState);
                return _result;
            }
            
            public ServiceReference.MySisEvo.Web.DataServis.Datas[] EndgetDataListXml(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                ServiceReference.MySisEvo.Web.DataServis.Datas[] _result = ((ServiceReference.MySisEvo.Web.DataServis.Datas[])(base.EndInvoke("getDataListXml", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetAlarmlar(string kul, System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[1];
                _args[0] = kul;
                System.IAsyncResult _result = base.BeginInvoke("getAlarmlar", _args, callback, asyncState);
                return _result;
            }
            
            public ServiceReference.MySisEvo.Web.DataServis.Alarmlar[] EndgetAlarmlar(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                ServiceReference.MySisEvo.Web.DataServis.Alarmlar[] _result = ((ServiceReference.MySisEvo.Web.DataServis.Alarmlar[])(base.EndInvoke("getAlarmlar", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginsetAlarmTanim(string Serinolar, ServiceReference.MySisEvo.Web.DataServis.AlarmT AlarmTan, System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[2];
                _args[0] = Serinolar;
                _args[1] = AlarmTan;
                System.IAsyncResult _result = base.BeginInvoke("setAlarmTanim", _args, callback, asyncState);
                return _result;
            }
            
            public void EndsetAlarmTanim(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                base.EndInvoke("setAlarmTanim", _args, result);
            }
            
            public System.IAsyncResult BegingetAraclar(string kulAd, System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[1];
                _args[0] = kulAd;
                System.IAsyncResult _result = base.BeginInvoke("getAraclar", _args, callback, asyncState);
                return _result;
            }
            
            public ServiceReference.MySisEvo.Web.DataServis.Araclar[] EndgetAraclar(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                ServiceReference.MySisEvo.Web.DataServis.Araclar[] _result = ((ServiceReference.MySisEvo.Web.DataServis.Araclar[])(base.EndInvoke("getAraclar", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginupdateArac(ServiceReference.MySisEvo.Web.DataServis.Araclar arac, System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[1];
                _args[0] = arac;
                System.IAsyncResult _result = base.BeginInvoke("updateArac", _args, callback, asyncState);
                return _result;
            }
            
            public void EndupdateArac(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                base.EndInvoke("updateArac", _args, result);
            }
            
            public System.IAsyncResult BegingetKullanici(string kulAd, string kulSifre, System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[2];
                _args[0] = kulAd;
                _args[1] = kulSifre;
                System.IAsyncResult _result = base.BeginInvoke("getKullanici", _args, callback, asyncState);
                return _result;
            }
            
            public ServiceReference.MySisEvo.Web.DataServis.Kullanici EndgetKullanici(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                ServiceReference.MySisEvo.Web.DataServis.Kullanici _result = ((ServiceReference.MySisEvo.Web.DataServis.Kullanici)(base.EndInvoke("getKullanici", _args, result)));
                return _result;
            }
        }
    }
}
// Auto generated configuration elements
// Generated client configuration:CustomBinding_DataServis1<>http://DataServis.svc<>http://localhost:2564/DataServis.svc
